### ISSUE TITLE
maven编译源码失败

### ISSUE THREAD

**Issue by cleverpig** [zhuchao941/maintainable-disconf-client#1]
@zhuchao941 你用的IDE工具是intellij什么版本？

**Comment by zhuchao941** [comment]
> @zhuchao941 你用的IDE工具是intellij什么版本？

把错误贴一下

**Comment by cleverpig** [comment]
编译过了，就是IDE对@Slf4j等lombok的annotation支持有问题，被标红了。

**Comment by zhuchao941** [comment]
> 编译过了，就是IDE对@slf4j等lombok的annotation支持有问题，被标红了。

lombok这块你在IDE里装下plugin就好，可以参考
https://jingyan.baidu.com/article/0a52e3f4e53ca1bf63ed725c.html

**Comment by cleverpig** [comment]
ok，已经妥了

**Comment by zhuchao941** [comment]
> ok，已经妥了

欢迎star ^^
