### ISSUE TITLE
maintable-disconf-client会把同步下来的配置注入到spring environment吗？

### ISSUE THREAD

**Issue by Holyangelmom** [zhuchao941/maintainable-disconf-client#2]
如题，大佬解答下

**Comment by zhuchao941** [comment]
会的，readme里也有写，是碰到什么问题了么

**Comment by Holyangelmom** [comment]
> 会的，readme里也有写，是碰到什么问题了么

怎么没有邮件通知问题被回复了呢。    sorry刚刚看到，我折腾了好几天发现disconf没能注入到environment，所以想用您这个版本试试。

**Comment by Holyangelmom** [comment]
有没有集成maintable-disconf-client的教程？仅仅引入maintable-disconf-client的pom就完了嘛？

**Comment by zhuchao941** [comment]
> 有没有集成maintable-disconf-client的教程？仅仅引入maintable-disconf-client的pom就完了嘛？

首先前提你得是基于spring-boot的项目。那么仅仅引入maintable-disconf-client的依赖就可以完成环境变量的注入。相关的disconf.properties也记得配置下。这些readme上都有写的。如果还有问题，可以再联系我

**Comment by Holyangelmom** [comment]
好的
